export const businessDevelopmentAreas = [
  {
    id: "business-language",
    title: "Business Language",
    plainTitle: "Make your offer easy to understand.",
    problem: "I struggle to explain what my business does and why someone should choose it.",
    support: "We help you describe what you offer, who it is for, and the problem it solves in language your customers understand.",
    outcome: "A clearer business introduction and consistent customer messaging.",
  },
  {
    id: "page-setup",
    title: "Page Setup & Optimization",
    plainTitle: "Give customers a clear first impression.",
    problem: "My business pages are missing, incomplete, or do not explain my offer clearly.",
    support: "We help set up and improve your business and social pages, with clear information, consistent branding, and an obvious way to get in touch.",
    outcome: "Business pages that help people understand your offer and take the next step.",
  },
  {
    id: "buyer-persona",
    title: "Buyer Persona Selection",
    plainTitle: "Know who you are trying to reach.",
    problem: "I am trying to sell to everyone, but I am not sure who actually needs my offer.",
    support: "We work with you to identify likely customers, understand their needs, and prioritise the audience your business should focus on.",
    outcome: "A practical customer profile to guide your messaging and marketing choices.",
  },
  {
    id: "marketing-strategy",
    title: "Marketing Strategy",
    plainTitle: "Choose a direction before you spend.",
    problem: "I do not know which channels to use or what my marketing should focus on.",
    support: "We connect your audience, offer, and budget to a focused marketing plan with clear priorities and ways to review progress.",
    outcome: "A marketing action plan built around your current business goals.",
  },
  {
    id: "execution-growth",
    title: "Execution & Business Growth Support",
    plainTitle: "Turn the plan into practical action.",
    problem: "I have ideas and plans, but need help deciding what to do next and getting it done.",
    support: "We help organise the next steps, coordinate agreed work, and review what is working as your business develops.",
    outcome: "Agreed priorities, practical delivery support, and progress reviews.",
  },
  {
    id: "sales-funnel",
    title: "Sales Funnel Support",
    plainTitle: "Create a clearer path from interest to enquiry.",
    problem: "People show interest, but enquiries and follow-ups are not turning into enough sales conversations.",
    support: "We review how people discover your business, enquire, and receive follow-up, then help you improve the steps between them.",
    outcome: "A clearer customer journey and a more organised follow-up process.",
  },
  {
    id: "retention",
    title: "After Support & Retention",
    plainTitle: "Keep the relationship going after the sale.",
    problem: "I need a better way to support customers and give them a reason to return.",
    support: "We help you plan after-sales communication, collect useful feedback, and improve how you stay in touch with existing customers.",
    outcome: "A practical customer care and retention plan.",
  },
] as const;

export const businessChallenges = [
  {
    id: "starting",
    label: "I want to start a business",
    title: "Give your idea a clear starting point.",
    description: "You do not need a finished business plan. We help you explain your offer, understand who it is for, and choose the first steps toward launch.",
    steps: ["Clarify your business idea", "Identify your ideal customer", "Plan your business presence"],
    href: "/services/business-development#business-language",
    linkLabel: "Explore startup support",
  },
  {
    id: "customers",
    label: "I need to reach customers",
    title: "Know who to reach—and how to reach them.",
    description: "If your business is ready but your marketing lacks direction, we help you focus on the right audience, a clearer message, and a practical marketing plan.",
    steps: ["Define your customer profile", "Improve your business pages", "Set your marketing priorities"],
    href: "/services/business-development#buyer-persona",
    linkLabel: "Explore customer growth support",
  },
  {
    id: "growth",
    label: "I want better sales & retention",
    title: "Build a stronger journey beyond the first enquiry.",
    description: "When interest is not leading to enough conversations or repeat business, we help you improve follow-up, sales processes, and ongoing customer support.",
    steps: ["Review the enquiry journey", "Organise sales follow-up", "Plan after-sales support"],
    href: "/services/business-development#sales-funnel",
    linkLabel: "Explore sales & retention support",
  },
] as const;
