export const businessDevelopmentAreas = [
  {
    id: "business-language",
    title: "Business Language",
    plainTitle: "Make your offer easy to understand.",
    exampleTitle: "The same coffee, but a different way of asking",
    example: "Imagine ordering coffee from a small street shop. You may simply say, “One coffee, please.” In a formal restaurant, you may speak differently because the place, service, and expectation are different. Your need is the same, but the way you communicate changes.",
    meaning: "Business works in the same way. Different customers have different problems, expectations, and ways of speaking. Business Language means choosing clear words that help the right customer understand your value. It is not about using difficult business terms. It is about saying the right thing, to the right person, in a way that feels natural to them.",
    imageBrief: "A customer ordering coffee in a refined café, showing how communication changes with the setting.",
    problem: "I struggle to explain what my business does and why someone should choose it.",
    support: "We help you describe what you offer, who it is for, and the problem it solves in language your customers understand.",
    outcome: "A clearer business introduction and consistent customer messaging.",
    suitableFor: "You have a business idea or offer, but find it hard to explain in a simple and confident way.",
    includes: ["A clear description of your business", "Your main customer problem and solution", "Simple messages for your website and business pages", "A short introduction you can use when speaking to customers"],
    process: ["We listen to your idea and ask simple questions.", "We identify what you offer and who it helps.", "We shape clear words you can use across your business."],
  },
  {
    id: "page-setup",
    title: "Page Setup & Optimization",
    plainTitle: "Give customers a clear first impression.",
    exampleTitle: "A shop can be open and still lose customers",
    example: "Imagine walking into a shop with no sign, no prices, and no clear place to ask for help. The products may be good, but most people will feel confused and leave. An online business page can create the same problem when important information is missing or hard to find.",
    meaning: "Page setup is the work of making your website and business profiles clear, complete, and easy to use. A visitor should quickly understand who you are, what you offer, and what to do next. Optimization means improving those pages so they work better for real customers—not simply making them look attractive.",
    imageBrief: "A business owner reviewing clear website and social page layouts on a laptop and phone.",
    problem: "My business pages are missing, incomplete, or do not explain my offer clearly.",
    support: "We help set up and improve your business and social pages, with clear information, consistent branding, and an obvious way to get in touch.",
    outcome: "Business pages that help people understand your offer and take the next step.",
    suitableFor: "Your business pages are missing, unfinished, or confusing for people who visit them.",
    includes: ["A review of your current business pages", "Clear profile and business information", "Better page structure and calls to action", "Consistent details across your main online pages"],
    process: ["We check what customers see today.", "We find missing or unclear information.", "We help organise and improve the pages that matter most."],
  },
  {
    id: "buyer-persona",
    title: "Buyer Persona Selection",
    plainTitle: "Know who you are trying to reach.",
    exampleTitle: "One pair of shoes cannot fit everyone",
    example: "A school shoe, a running shoe, and a formal shoe all solve different problems. If a shop describes every shoe in the same way to every person, the message becomes weak. The shop needs to know who each product is for and what that person cares about.",
    meaning: "A buyer persona is a simple picture of the customer you want to help. It describes their situation, needs, worries, and buying reasons. Choosing a buyer persona gives your business a clear focus, so your message and marketing speak to people who are more likely to need your offer.",
    imageBrief: "An adviser and founder comparing simple customer profiles and choosing one clear audience.",
    problem: "I am trying to sell to everyone, but I am not sure who actually needs my offer.",
    support: "We work with you to identify likely customers, understand their needs, and prioritise the audience your business should focus on.",
    outcome: "A practical customer profile to guide your messaging and marketing choices.",
    suitableFor: "You know what you want to sell, but you are not sure who is most likely to need or buy it.",
    includes: ["A clear picture of your ideal customer", "Their main needs and problems", "Where they may look for help", "Messages that speak to what matters to them"],
    process: ["We learn about your offer and market.", "We compare the customer groups you could serve.", "We choose a clear audience to focus on first."],
  },
  {
    id: "marketing-strategy",
    title: "Marketing Strategy",
    plainTitle: "Choose a direction before you spend.",
    exampleTitle: "A loud message in the wrong place is still missed",
    example: "Imagine handing out hundreds of restaurant flyers in an empty office area on a public holiday. You are promoting the business, but the right people are not there. More activity does not always mean better marketing.",
    meaning: "A marketing strategy decides who you want to reach, what you need to say, where you should say it, and what result you want. It helps you spend time and money with a clear purpose instead of posting everywhere and hoping something works.",
    imageBrief: "A business owner and adviser planning marketing channels, content, and timing around a table.",
    problem: "I do not know which channels to use or what my marketing should focus on.",
    support: "We connect your audience, offer, and budget to a focused marketing plan with clear priorities and ways to review progress.",
    outcome: "A marketing action plan built around your current business goals.",
    suitableFor: "You want more people to know about your business, but you do not know what to say or where to promote it.",
    includes: ["Clear marketing goals", "Recommended channels for your audience", "Content and campaign priorities", "Simple ways to review what is working"],
    process: ["We agree what you want marketing to achieve.", "We match your audience with useful channels.", "We create a focused plan you can follow."],
  },
  {
    id: "execution-growth",
    title: "Execution & Business Growth Support",
    plainTitle: "Turn the plan into practical action.",
    exampleTitle: "A recipe does not cook the meal",
    example: "You can have a perfect recipe, buy every ingredient, and still have no meal until someone starts cooking. A business plan is similar. Ideas only create value when the right actions happen in the right order.",
    meaning: "Execution means turning plans into real work. Growth support helps you choose priorities, organise responsibilities, complete important tasks, and review progress. The goal is to keep the business moving without trying to do everything at once.",
    imageBrief: "A small team moving tasks from a business plan into action and reviewing progress together.",
    problem: "I have ideas and plans, but need help deciding what to do next and getting it done.",
    support: "We help organise the next steps, coordinate agreed work, and review what is working as your business develops.",
    outcome: "Agreed priorities, practical delivery support, and progress reviews.",
    suitableFor: "You have a plan or several ideas, but need help choosing priorities and turning them into action.",
    includes: ["A clear list of priorities", "Simple actions and responsibilities", "Support with agreed business tasks", "Regular progress checks and next steps"],
    process: ["We review your goals and current position.", "We agree what should happen first.", "We support the work and review progress with you."],
  },
  {
    id: "sales-funnel",
    title: "Sales Funnel Support",
    plainTitle: "Create a clearer path from interest to enquiry.",
    exampleTitle: "Interest can disappear when no one follows up",
    example: "Imagine a customer enters a shop, asks about a product, and leaves their phone number. If nobody calls them back, that interest is lost. The business found a possible customer but did not help them take the next step.",
    meaning: "A sales funnel is the path a person takes from first hearing about your business to becoming a customer. Sales funnel support makes each step clearer: attracting interest, answering questions, collecting enquiries, following up, and helping the customer decide.",
    imageBrief: "An adviser mapping the customer path from first interest to enquiry, follow-up, and sale.",
    problem: "People show interest, but enquiries and follow-ups are not turning into enough sales conversations.",
    support: "We review how people discover your business, enquire, and receive follow-up, then help you improve the steps between them.",
    outcome: "A clearer customer journey and a more organised follow-up process.",
    suitableFor: "People show interest in your business, but too few become real enquiries or customers.",
    includes: ["A review of your customer journey", "Clear steps from interest to enquiry", "A simple follow-up process", "Ways to keep track of sales opportunities"],
    process: ["We map how customers reach you today.", "We find where interest is being lost.", "We improve the steps and follow-up between enquiry and sale."],
  },
  {
    id: "retention",
    title: "After Support & Retention",
    plainTitle: "Keep the relationship going after the sale.",
    exampleTitle: "Good service should not end at payment",
    example: "Think about two shops selling the same product. One forgets you after payment. The other checks that everything is working, answers questions, and remembers what you need next time. Most people will trust and return to the second shop.",
    meaning: "After support means helping customers after they buy. Retention means giving them good reasons to stay with your business, return, and recommend you. It grows through useful communication, reliable support, feedback, and care—not through constant sales messages.",
    imageBrief: "A business owner having a warm follow-up conversation with a satisfied returning customer.",
    problem: "I need a better way to support customers and give them a reason to return.",
    support: "We help you plan after-sales communication, collect useful feedback, and improve how you stay in touch with existing customers.",
    outcome: "A practical customer care and retention plan.",
    suitableFor: "You want customers to feel supported, return to your business, and recommend you to other people.",
    includes: ["An after-sales communication plan", "Simple customer check-ins", "A useful feedback process", "Ideas for repeat business and referrals"],
    process: ["We review what happens after a customer buys.", "We identify useful moments to stay in touch.", "We create a simple plan for support, feedback, and return visits."],
  },
] as const;

export const businessChallenges = [
  {
    id: "starting",
    label: "I want to start a business",
    title: "Give your idea a clear starting point.",
    description: "You do not need a finished business plan. We help you explain your offer, understand who it is for, and choose the first steps toward launch.",
    steps: ["Clarify your business idea", "Identify your ideal customer", "Plan your business presence"],
    href: "/services/business-development/business-language",
    linkLabel: "Explore startup support",
  },
  {
    id: "customers",
    label: "I need to reach customers",
    title: "Know who to reach—and how to reach them.",
    description: "If your business is ready but your marketing lacks direction, we help you focus on the right audience, a clearer message, and a practical marketing plan.",
    steps: ["Define your customer profile", "Improve your business pages", "Set your marketing priorities"],
    href: "/services/business-development/buyer-persona",
    linkLabel: "Explore customer growth support",
  },
  {
    id: "growth",
    label: "I want better sales & retention",
    title: "Build a stronger journey beyond the first enquiry.",
    description: "When interest is not leading to enough conversations or repeat business, we help you improve follow-up, sales processes, and ongoing customer support.",
    steps: ["Review the enquiry journey", "Organise sales follow-up", "Plan after-sales support"],
    href: "/services/business-development/sales-funnel",
    linkLabel: "Explore sales & retention support",
  },
] as const;
