ALTER TABLE "Project" ADD COLUMN "priority" TEXT DEFAULT 'medium';
ALTER TABLE "Project" ADD COLUMN "budget" DOUBLE PRECISION;
ALTER TABLE "Project" ADD COLUMN "budgetSpent" DOUBLE PRECISION DEFAULT 0;
ALTER TABLE "Project" ADD COLUMN "progress" INTEGER DEFAULT 0;
ALTER TABLE "Project" ADD COLUMN "serviceType" TEXT;
ALTER TYPE "ProjectStatus" ADD VALUE 'PLANNING';
ALTER TYPE "ProjectStatus" ADD VALUE 'IN_REVIEW';