import type { AdminService } from "@/types/dashboard/admin/servicesType";

// TODO: Replace with service catalog, proposal, project, and financial data from the backend.
export const adminServicesMock: AdminService[] = [
  { id: "srv-website", name: "Website Development", pillar: "Development", description: "Conversion-focused marketing sites and scalable digital platforms.", status: "active", startingPrice: "From €6,000", deliveryWindow: "6–10 weeks", activeProjects: 8, newLeads: 34, conversionRate: 23.5, revenue: 34200, deliverables: ["Discovery", "UX/UI", "Development"] },
  { id: "srv-marketing", name: "Digital Marketing", pillar: "Digital", description: "Integrated acquisition campaigns built for measurable pipeline growth.", status: "active", startingPrice: "From €2,500/mo", deliveryWindow: "Monthly retainer", activeProjects: 6, newLeads: 28, conversionRate: 21.4, revenue: 21800, deliverables: ["Campaigns", "Content", "Reporting"] },
  { id: "srv-sales", name: "Sales Support", pillar: "Sales", description: "Outbound systems, sales enablement, and qualified meeting generation.", status: "active", startingPrice: "From €3,000/mo", deliveryWindow: "Monthly retainer", activeProjects: 4, newLeads: 21, conversionRate: 14.3, revenue: 16000, deliverables: ["Outbound", "Playbooks", "Enablement"] },
  { id: "srv-mobile", name: "Mobile Applications", pillar: "Development", description: "Native-feeling mobile products for iOS and Android audiences.", status: "paused", startingPrice: "From €14,000", deliveryWindow: "12–16 weeks", activeProjects: 2, newLeads: 13, conversionRate: 7.7, revenue: 12500, deliverables: ["Product strategy", "App build", "QA"] },
  { id: "srv-consulting", name: "Growth Strategy", pillar: "Strategy", description: "Focused advisory engagements for positioning, GTM, and business growth.", status: "draft", startingPrice: "From €1,800", deliveryWindow: "2–4 weeks", activeProjects: 0, newLeads: 7, conversionRate: 0, revenue: 0, deliverables: ["Audit", "Roadmap", "Workshop"] },
  { id: "srv-branding", name: "Branding & Identity", pillar: "Strategy", description: "Clear brand systems that make a business easier to recognise and choose.", status: "active", startingPrice: "From €4,000", deliveryWindow: "4–6 weeks", activeProjects: 3, newLeads: 15, conversionRate: 20, revenue: 11800, deliverables: ["Positioning", "Visual identity", "Guidelines"] },
];
