import { Payment } from "@/types/dashboard/client/paymentTypes";

export const paymentsMockData: Payment[] = [
  {
    id: "1",
    invoiceId: "INV-001",
    clientName: "Acme Corp",
    projectName: "Website Redesign",
    amount: 2500.0,
    date: "2026-07-15",
    method: "Credit Card",
    status: "paid",
  },
  {
    id: "2",
    invoiceId: "INV-002",
    clientName: "Globex Inc",
    projectName: "Mobile App Development",
    amount: 8750.0,
    date: "2026-07-14",
    method: "Bank Transfer",
    status: "pending",
  },
  {
    id: "3",
    invoiceId: "INV-003",
    clientName: "Initech",
    projectName: "Digital Marketing Campaign",
    amount: 3200.0,
    date: "2026-07-10",
    method: "PayPal",
    status: "overdue",
  },
  {
    id: "4",
    invoiceId: "INV-004",
    clientName: "Umbrella Corp",
    projectName: "Sales Support Retainer",
    amount: 4200.0,
    date: "2026-07-08",
    method: "Credit Card",
    status: "failed",
  },
  {
    id: "5",
    invoiceId: "INV-005",
    clientName: "Stark Industries",
    projectName: "Website Maintenance",
    amount: 1500.0,
    date: "2026-07-12",
    method: "Bank Transfer",
    status: "refunded",
  },
  {
    id: "6",
    invoiceId: "INV-006",
    clientName: "Wayne Enterprises",
    projectName: "SEO Optimization",
    amount: 2800.0,
    date: "2026-07-01",
    method: "PayPal",
    status: "paid",
  },
];
