import {
  Project,
  Industry,
  ServiceType,
  ProjectStatus,
  ProjectPriority,
} from "@/types/dashboard/client/projectsType";

export const industries: Industry[] = [
  "Fashion Tech",
  "IT & Software",
  "Medical Industry",
  "Beauty Industry",
  "Manufacturing / Industrial",
  "Fintech",
  "E-commerce",
  "Education",
];

export const serviceTypes: ServiceType[] = [
  "Website Development",
  "Web Application",
  "Mobile Application",
  "Digital Marketing",
  "SEO",
  "Branding",
  "UI/UX Design",
  "Sales & Marketing",
  "Business Consultation",
  "Custom Enterprise Solutions",
];

export const statuses: ProjectStatus[] = [
  "active",
  "completed",
  "on-hold",
  "planning",
  "in-review",
];

export const priorities: ProjectPriority[] = [
  "low",
  "medium",
  "high",
  "critical",
];

const teamMembers = [
  { id: "1", name: "Alice Chen", role: "Lead Developer", avatar: "AC" },
  { id: "2", name: "Bob Smith", role: "UX Designer", avatar: "BS" },
  { id: "3", name: "Carla Delgado", role: "Project Manager", avatar: "CD" },
  { id: "4", name: "David Kim", role: "Backend Developer", avatar: "DK" },
  { id: "5", name: "Elena Rossi", role: "Frontend Developer", avatar: "ER" },
];

const randomDate = (start: Date, days: number) => {
  const d = new Date(start);
  d.setDate(d.getDate() + Math.floor(Math.random() * days));
  return d;
};

export const mockProjects: Project[] = [
  {
    id: "1",
    name: "Luxe Fashion E‑commerce Platform",
    clientCompany: "Velvet & Co.",
    industry: "Fashion Tech",
    serviceType: "Website Development",
    status: "active",
    priority: "high",
    budget: 75000,
    budgetSpent: 54000,
    timeline: {
      start: new Date("2025-11-01"),
      end: new Date("2026-04-30"),
    },
    progress: 72,
    assignedTeam: [teamMembers[0], teamMembers[2], teamMembers[4]],
    dueDate: new Date("2026-04-30"),
    lastUpdated: new Date("2026-03-10"),
    description:
      "A premium e-commerce platform for Velvet & Co.'s luxury fashion line, featuring AI-powered size recommendations, virtual try-on, and seamless checkout with multiple payment gateways including crypto.",
    clientContact: {
      name: "Isabella Laurent",
      email: "i.laurent@velvetco.com",
      phone: "+1 (212) 555-0187",
      avatar: "IL",
    },
    milestones: [
      {
        id: "m1-1",
        title: "Design System & Wireframes",
        status: "completed",
        dueDate: new Date("2025-12-15"),
      },
      {
        id: "m1-2",
        title: "Frontend Development",
        status: "completed",
        dueDate: new Date("2026-02-01"),
      },
      {
        id: "m1-3",
        title: "Payment Integration",
        status: "in-progress",
        dueDate: new Date("2026-03-25"),
      },
      {
        id: "m1-4",
        title: "AI Size Recommendation Engine",
        status: "pending",
        dueDate: new Date("2026-04-15"),
      },
      {
        id: "m1-5",
        title: "Final QA & Launch",
        status: "pending",
        dueDate: new Date("2026-04-30"),
      },
    ],
    files: [
      {
        id: "f1-1",
        name: "Brand_Guidelines.pdf",
        type: "pdf",
        size: "4.2 MB",
        uploadedBy: "Isabella Laurent",
        uploadedAt: new Date("2025-11-05"),
        url: "#",
      },
      {
        id: "f1-2",
        name: "Homepage_Design_V3.fig",
        type: "figma",
        size: "12.8 MB",
        uploadedBy: "Bob Smith",
        uploadedAt: new Date("2025-12-20"),
        url: "#",
      },
      {
        id: "f1-3",
        name: "API_Documentation.pdf",
        type: "pdf",
        size: "1.5 MB",
        uploadedBy: "David Kim",
        uploadedAt: new Date("2026-03-01"),
        url: "#",
      },
      {
        id: "f1-4",
        name: "Product_Images_Batch1.zip",
        type: "zip",
        size: "45.3 MB",
        uploadedBy: "Isabella Laurent",
        uploadedAt: new Date("2026-03-08"),
        url: "#",
      },
    ],
    activity: [
      {
        id: "a1-1",
        action: "Project initiated",
        performedBy: "Carla Delgado",
        timestamp: new Date("2025-11-01"),
      },
      {
        id: "a1-2",
        action: "Milestone 'Design System & Wireframes' completed",
        performedBy: "Bob Smith",
        timestamp: new Date("2025-12-15"),
      },
      {
        id: "a1-3",
        action: "File 'Homepage_Design_V3.fig' uploaded",
        performedBy: "Bob Smith",
        timestamp: new Date("2025-12-20"),
      },
      {
        id: "a1-4",
        action: "Milestone 'Frontend Development' completed",
        performedBy: "Elena Rossi",
        timestamp: new Date("2026-02-01"),
      },
      {
        id: "a1-5",
        action: "Payment gateway integration started",
        performedBy: "Alice Chen",
        timestamp: new Date("2026-02-15"),
      },
      {
        id: "a1-6",
        action: "File 'Product_Images_Batch1.zip' uploaded",
        performedBy: "Isabella Laurent",
        timestamp: new Date("2026-03-08"),
      },
    ],
  },
  {
    id: "2",
    name: "Hospital ERP System",
    clientCompany: "MediCore Group",
    industry: "Medical Industry",
    serviceType: "Custom Enterprise Solutions",
    status: "active",
    priority: "critical",
    budget: 210000,
    budgetSpent: 94500,
    timeline: {
      start: new Date("2025-09-15"),
      end: new Date("2026-08-15"),
    },
    progress: 45,
    assignedTeam: [teamMembers[1], teamMembers[3], teamMembers[0]],
    dueDate: new Date("2026-08-15"),
    lastUpdated: new Date("2026-03-12"),
    description:
      "Comprehensive hospital management system covering patient records, appointment scheduling, billing, inventory management, and HIPAA-compliant data handling across MediCore's network of 12 hospitals.",
    clientContact: {
      name: "Dr. Marcus Webb",
      email: "marcus.webb@medicore.com",
      phone: "+1 (415) 555-0293",
      avatar: "MW",
    },
    milestones: [
      {
        id: "m2-1",
        title: "Requirements Analysis & Architecture",
        status: "completed",
        dueDate: new Date("2025-11-30"),
      },
      {
        id: "m2-2",
        title: "Patient Records Module",
        status: "completed",
        dueDate: new Date("2026-01-31"),
      },
      {
        id: "m2-3",
        title: "Appointment Scheduling System",
        status: "in-progress",
        dueDate: new Date("2026-04-15"),
      },
      {
        id: "m2-4",
        title: "Billing & Insurance Integration",
        status: "pending",
        dueDate: new Date("2026-06-30"),
      },
      {
        id: "m2-5",
        title: "Inventory & Pharmacy Management",
        status: "pending",
        dueDate: new Date("2026-07-31"),
      },
      {
        id: "m2-6",
        title: "System Integration Testing & Deployment",
        status: "pending",
        dueDate: new Date("2026-08-15"),
      },
    ],
    files: [
      {
        id: "f2-1",
        name: "HIPAA_Compliance_Checklist.pdf",
        type: "pdf",
        size: "890 KB",
        uploadedBy: "Dr. Marcus Webb",
        uploadedAt: new Date("2025-09-20"),
        url: "#",
      },
      {
        id: "f2-2",
        name: "System_Architecture_Diagram.pdf",
        type: "pdf",
        size: "3.1 MB",
        uploadedBy: "Alice Chen",
        uploadedAt: new Date("2025-11-15"),
        url: "#",
      },
      {
        id: "f2-3",
        name: "Database_Schema_V2.sql",
        type: "doc",
        size: "256 KB",
        uploadedBy: "David Kim",
        uploadedAt: new Date("2026-01-10"),
        url: "#",
      },
    ],
    activity: [
      {
        id: "a2-1",
        action: "Project kickoff meeting",
        performedBy: "Carla Delgado",
        timestamp: new Date("2025-09-15"),
      },
      {
        id: "a2-2",
        action: "Milestone 'Requirements Analysis' completed",
        performedBy: "Bob Smith",
        timestamp: new Date("2025-11-30"),
      },
      {
        id: "a2-3",
        action: "File 'Database_Schema_V2.sql' uploaded",
        performedBy: "David Kim",
        timestamp: new Date("2026-01-10"),
      },
      {
        id: "a2-4",
        action: "Milestone 'Patient Records Module' completed",
        performedBy: "Alice Chen",
        timestamp: new Date("2026-01-31"),
      },
      {
        id: "a2-5",
        action: "Appointment Scheduling development started",
        performedBy: "David Kim",
        timestamp: new Date("2026-02-05"),
      },
      {
        id: "a2-6",
        action: "Security audit conducted",
        performedBy: "Dr. Marcus Webb",
        timestamp: new Date("2026-03-10"),
      },
    ],
  },
  {
    id: "3",
    name: "Mobile Banking App",
    clientCompany: "Finwise Bank",
    industry: "Fintech",
    serviceType: "Mobile Application",
    status: "in-review",
    priority: "high",
    budget: 120000,
    budgetSpent: 114000,
    timeline: {
      start: new Date("2026-01-10"),
      end: new Date("2026-05-20"),
    },
    progress: 95,
    assignedTeam: [teamMembers[0], teamMembers[1], teamMembers[3]],
    dueDate: new Date("2026-05-20"),
    lastUpdated: new Date("2026-03-14"),
    description:
      "Cross-platform mobile banking application with biometric authentication, real-time transaction monitoring, peer-to-peer transfers, investment portfolio tracking, and AI-driven spending insights.",
    clientContact: {
      name: "Raj Patel",
      email: "raj.patel@finwise.com",
      phone: "+1 (650) 555-0412",
      avatar: "RP",
    },
    milestones: [
      {
        id: "m3-1",
        title: "UI/UX Design & Prototyping",
        status: "completed",
        dueDate: new Date("2026-02-05"),
      },
      {
        id: "m3-2",
        title: "Core Banking Features",
        status: "completed",
        dueDate: new Date("2026-03-01"),
      },
      {
        id: "m3-3",
        title: "AI Spending Insights Module",
        status: "completed",
        dueDate: new Date("2026-03-20"),
      },
      {
        id: "m3-4",
        title: "Security & Penetration Testing",
        status: "in-progress",
        dueDate: new Date("2026-04-10"),
      },
      {
        id: "m3-5",
        title: "App Store Submission",
        status: "pending",
        dueDate: new Date("2026-05-20"),
      },
    ],
    files: [
      {
        id: "f3-1",
        name: "Finwise_Brand_Assets.zip",
        type: "zip",
        size: "28.5 MB",
        uploadedBy: "Raj Patel",
        uploadedAt: new Date("2026-01-12"),
        url: "#",
      },
      {
        id: "f3-2",
        name: "App_Flow_Diagrams.fig",
        type: "figma",
        size: "8.3 MB",
        uploadedBy: "Bob Smith",
        uploadedAt: new Date("2026-02-01"),
        url: "#",
      },
      {
        id: "f3-3",
        name: "Security_Test_Report.pdf",
        type: "pdf",
        size: "1.7 MB",
        uploadedBy: "Alice Chen",
        uploadedAt: new Date("2026-03-25"),
        url: "#",
      },
      {
        id: "f3-4",
        name: "App_Preview_Screenshots.zip",
        type: "image",
        size: "15.2 MB",
        uploadedBy: "Elena Rossi",
        uploadedAt: new Date("2026-03-28"),
        url: "#",
      },
    ],
    activity: [
      {
        id: "a3-1",
        action: "Project initiated",
        performedBy: "Carla Delgado",
        timestamp: new Date("2026-01-10"),
      },
      {
        id: "a3-2",
        action: "Milestone 'UI/UX Design & Prototyping' completed",
        performedBy: "Bob Smith",
        timestamp: new Date("2026-02-05"),
      },
      {
        id: "a3-3",
        action: "Milestone 'Core Banking Features' completed",
        performedBy: "Alice Chen",
        timestamp: new Date("2026-03-01"),
      },
      {
        id: "a3-4",
        action: "Milestone 'AI Spending Insights Module' completed",
        performedBy: "David Kim",
        timestamp: new Date("2026-03-20"),
      },
      {
        id: "a3-5",
        action: "Security penetration testing initiated",
        performedBy: "Alice Chen",
        timestamp: new Date("2026-03-22"),
      },
      {
        id: "a3-6",
        action: "File 'App_Preview_Screenshots.zip' uploaded",
        performedBy: "Elena Rossi",
        timestamp: new Date("2026-03-28"),
      },
    ],
  },
  {
    id: "4",
    name: "Beauty Booking Platform",
    clientCompany: "Glow Studio",
    industry: "Beauty Industry",
    serviceType: "Web Application",
    status: "planning",
    priority: "medium",
    budget: 45000,
    budgetSpent: 0,
    timeline: {
      start: new Date("2026-04-01"),
      end: new Date("2026-06-30"),
    },
    progress: 0,
    assignedTeam: [teamMembers[2], teamMembers[4]],
    dueDate: new Date("2026-06-30"),
    lastUpdated: new Date("2026-03-01"),
    description:
      "Online booking and management platform for Glow Studio's beauty services, including real-time availability calendar, automated reminders, customer profiles, and integrated payment processing.",
    clientContact: {
      name: "Sophia Chen",
      email: "sophia@glowstudio.com",
      phone: "+1 (310) 555-0765",
      avatar: "SC",
    },
    milestones: [
      {
        id: "m4-1",
        title: "Discovery & Requirements Workshop",
        status: "pending",
        dueDate: new Date("2026-04-15"),
      },
      {
        id: "m4-2",
        title: "UI/UX Design",
        status: "pending",
        dueDate: new Date("2026-05-01"),
      },
      {
        id: "m4-3",
        title: "Frontend Development",
        status: "pending",
        dueDate: new Date("2026-05-30"),
      },
      {
        id: "m4-4",
        title: "Backend & Payment Integration",
        status: "pending",
        dueDate: new Date("2026-06-20"),
      },
      {
        id: "m4-5",
        title: "Testing & Launch",
        status: "pending",
        dueDate: new Date("2026-06-30"),
      },
    ],
    files: [
      {
        id: "f4-1",
        name: "Glow_Studio_Service_List.xlsx",
        type: "doc",
        size: "124 KB",
        uploadedBy: "Sophia Chen",
        uploadedAt: new Date("2026-03-01"),
        url: "#",
      },
    ],
    activity: [
      {
        id: "a4-1",
        action: "Project proposal accepted",
        performedBy: "Carla Delgado",
        timestamp: new Date("2026-02-25"),
      },
      {
        id: "a4-2",
        action: "Contract signed",
        performedBy: "Carla Delgado",
        timestamp: new Date("2026-03-01"),
      },
      {
        id: "a4-3",
        action: "File 'Glow_Studio_Service_List.xlsx' uploaded",
        performedBy: "Sophia Chen",
        timestamp: new Date("2026-03-01"),
      },
    ],
  },
  {
    id: "5",
    name: "SEO & Content Overhaul",
    clientCompany: "TechSphere Inc.",
    industry: "IT & Software",
    serviceType: "SEO",
    status: "completed",
    priority: "medium",
    budget: 28000,
    budgetSpent: 28000,
    timeline: {
      start: new Date("2025-08-01"),
      end: new Date("2026-02-28"),
    },
    progress: 100,
    assignedTeam: [teamMembers[3], teamMembers[0]],
    dueDate: new Date("2026-02-28"),
    lastUpdated: new Date("2026-03-01"),
    description:
      "Complete SEO audit and content strategy overhaul for TechSphere's website and blog, including keyword optimization, technical SEO fixes, backlink building, and content marketing plan.",
    clientContact: {
      name: "Thomas Keller",
      email: "t.keller@techsphere.com",
      phone: "+1 (512) 555-0934",
      avatar: "TK",
    },
    milestones: [
      {
        id: "m5-1",
        title: "Technical SEO Audit",
        status: "completed",
        dueDate: new Date("2025-09-15"),
      },
      {
        id: "m5-2",
        title: "Keyword Research & Strategy",
        status: "completed",
        dueDate: new Date("2025-10-31"),
      },
      {
        id: "m5-3",
        title: "Content Optimization",
        status: "completed",
        dueDate: new Date("2025-12-15"),
      },
      {
        id: "m5-4",
        title: "Backlink Building Campaign",
        status: "completed",
        dueDate: new Date("2026-01-31"),
      },
      {
        id: "m5-5",
        title: "Final Analytics Report & Handoff",
        status: "completed",
        dueDate: new Date("2026-02-28"),
      },
    ],
    files: [
      {
        id: "f5-1",
        name: "SEO_Audit_Report.pdf",
        type: "pdf",
        size: "5.6 MB",
        uploadedBy: "David Kim",
        uploadedAt: new Date("2025-09-15"),
        url: "#",
      },
      {
        id: "f5-2",
        name: "Keyword_Research_Matrix.xlsx",
        type: "doc",
        size: "340 KB",
        uploadedBy: "Alice Chen",
        uploadedAt: new Date("2025-10-31"),
        url: "#",
      },
      {
        id: "f5-3",
        name: "Content_Calendar_Q4_2025.xlsx",
        type: "doc",
        size: "215 KB",
        uploadedBy: "Alice Chen",
        uploadedAt: new Date("2025-11-05"),
        url: "#",
      },
      {
        id: "f5-4",
        name: "Final_ROI_Report.pdf",
        type: "pdf",
        size: "2.1 MB",
        uploadedBy: "David Kim",
        uploadedAt: new Date("2026-02-28"),
        url: "#",
      },
    ],
    activity: [
      {
        id: "a5-1",
        action: "Project kickoff",
        performedBy: "Carla Delgado",
        timestamp: new Date("2025-08-01"),
      },
      {
        id: "a5-2",
        action: "Milestone 'Technical SEO Audit' completed",
        performedBy: "David Kim",
        timestamp: new Date("2025-09-15"),
      },
      {
        id: "a5-3",
        action: "Milestone 'Keyword Research & Strategy' completed",
        performedBy: "Alice Chen",
        timestamp: new Date("2025-10-31"),
      },
      {
        id: "a5-4",
        action: "Milestone 'Content Optimization' completed",
        performedBy: "Alice Chen",
        timestamp: new Date("2025-12-15"),
      },
      {
        id: "a5-5",
        action: "Milestone 'Backlink Building Campaign' completed",
        performedBy: "David Kim",
        timestamp: new Date("2026-01-31"),
      },
      {
        id: "a5-6",
        action: "Project completed and handed off to client",
        performedBy: "Carla Delgado",
        timestamp: new Date("2026-02-28"),
      },
    ],
  },
  {
    id: "6",
    name: "Brand Identity & Marketing Campaign",
    clientCompany: "Nova Beauty",
    industry: "Beauty Industry",
    serviceType: "Branding",
    status: "active",
    priority: "low",
    budget: 32000,
    budgetSpent: 9600,
    timeline: {
      start: new Date("2026-02-15"),
      end: new Date("2026-05-15"),
    },
    progress: 30,
    assignedTeam: [teamMembers[1], teamMembers[2]],
    dueDate: new Date("2026-05-15"),
    lastUpdated: new Date("2026-03-10"),
    description:
      "Complete brand identity refresh for Nova Beauty including logo redesign, brand guidelines, packaging design, and a coordinated social media marketing campaign for their new product launch.",
    clientContact: {
      name: "Mia Nakamura",
      email: "mia@novabeauty.com",
      phone: "+1 (323) 555-0621",
      avatar: "MN",
    },
    milestones: [
      {
        id: "m6-1",
        title: "Brand Discovery & Research",
        status: "completed",
        dueDate: new Date("2026-03-01"),
      },
      {
        id: "m6-2",
        title: "Logo & Visual Identity Design",
        status: "in-progress",
        dueDate: new Date("2026-03-30"),
      },
      {
        id: "m6-3",
        title: "Brand Guidelines Documentation",
        status: "pending",
        dueDate: new Date("2026-04-15"),
      },
      {
        id: "m6-4",
        title: "Packaging Design Concepts",
        status: "pending",
        dueDate: new Date("2026-04-30"),
      },
      {
        id: "m6-5",
        title: "Marketing Campaign Launch",
        status: "pending",
        dueDate: new Date("2026-05-15"),
      },
    ],
    files: [
      {
        id: "f6-1",
        name: "Nova_Beauty_Current_Logo.ai",
        type: "image",
        size: "8.7 MB",
        uploadedBy: "Mia Nakamura",
        uploadedAt: new Date("2026-02-15"),
        url: "#",
      },
      {
        id: "f6-2",
        name: "Brand_Moodboard.pdf",
        type: "pdf",
        size: "3.2 MB",
        uploadedBy: "Bob Smith",
        uploadedAt: new Date("2026-02-28"),
        url: "#",
      },
      {
        id: "f6-3",
        name: "Logo_Concepts_V1.fig",
        type: "figma",
        size: "5.4 MB",
        uploadedBy: "Bob Smith",
        uploadedAt: new Date("2026-03-10"),
        url: "#",
      },
    ],
    activity: [
      {
        id: "a6-1",
        action: "Project initiated",
        performedBy: "Carla Delgado",
        timestamp: new Date("2026-02-15"),
      },
      {
        id: "a6-2",
        action: "File 'Nova_Beauty_Current_Logo.ai' uploaded",
        performedBy: "Mia Nakamura",
        timestamp: new Date("2026-02-15"),
      },
      {
        id: "a6-3",
        action: "Milestone 'Brand Discovery & Research' completed",
        performedBy: "Bob Smith",
        timestamp: new Date("2026-03-01"),
      },
      {
        id: "a6-4",
        action: "Logo design concepts presented to client",
        performedBy: "Bob Smith",
        timestamp: new Date("2026-03-10"),
      },
    ],
  },
  {
    id: "7",
    name: "Manufacturing ERP – Production Module",
    clientCompany: "Industrial Flow Ltd.",
    industry: "Manufacturing / Industrial",
    serviceType: "Custom Enterprise Solutions",
    status: "on-hold",
    priority: "high",
    budget: 180000,
    budgetSpent: 108000,
    timeline: {
      start: new Date("2025-10-01"),
      end: new Date("2026-07-01"),
    },
    progress: 60,
    assignedTeam: [
      teamMembers[0],
      teamMembers[1],
      teamMembers[3],
      teamMembers[4],
    ],
    dueDate: new Date("2026-07-01"),
    lastUpdated: new Date("2026-02-20"),
    description:
      "Specialized production module for Industrial Flow's existing ERP system, featuring real-time production line monitoring, quality control tracking, raw material inventory management, and predictive maintenance alerts using IoT sensors.",
    clientContact: {
      name: "James O'Brien",
      email: "j.obrien@industrialflow.com",
      phone: "+1 (248) 555-0147",
      avatar: "JO",
    },
    milestones: [
      {
        id: "m7-1",
        title: "System Analysis & IoT Integration Plan",
        status: "completed",
        dueDate: new Date("2025-11-15"),
      },
      {
        id: "m7-2",
        title: "Production Line Monitoring Dashboard",
        status: "completed",
        dueDate: new Date("2026-01-15"),
      },
      {
        id: "m7-3",
        title: "Quality Control Tracking System",
        status: "in-progress",
        dueDate: new Date("2026-03-15"),
      },
      {
        id: "m7-4",
        title: "Inventory Management Integration",
        status: "pending",
        dueDate: new Date("2026-05-01"),
      },
      {
        id: "m7-5",
        title: "Predictive Maintenance AI Module",
        status: "pending",
        dueDate: new Date("2026-06-15"),
      },
      {
        id: "m7-6",
        title: "System Testing & Factory Deployment",
        status: "pending",
        dueDate: new Date("2026-07-01"),
      },
    ],
    files: [
      {
        id: "f7-1",
        name: "Factory_Layout_Schematics.pdf",
        type: "pdf",
        size: "18.3 MB",
        uploadedBy: "James O'Brien",
        uploadedAt: new Date("2025-10-05"),
        url: "#",
      },
      {
        id: "f7-2",
        name: "IoT_Sensor_Specifications.pdf",
        type: "pdf",
        size: "2.8 MB",
        uploadedBy: "David Kim",
        uploadedAt: new Date("2025-11-01"),
        url: "#",
      },
      {
        id: "f7-3",
        name: "Dashboard_Mockups.fig",
        type: "figma",
        size: "9.1 MB",
        uploadedBy: "Bob Smith",
        uploadedAt: new Date("2025-12-20"),
        url: "#",
      },
      {
        id: "f7-4",
        name: "QC_Module_Source.zip",
        type: "zip",
        size: "32.6 MB",
        uploadedBy: "Alice Chen",
        uploadedAt: new Date("2026-02-18"),
        url: "#",
      },
    ],
    activity: [
      {
        id: "a7-1",
        action: "Project kickoff",
        performedBy: "Carla Delgado",
        timestamp: new Date("2025-10-01"),
      },
      {
        id: "a7-2",
        action: "Milestone 'System Analysis & IoT Plan' completed",
        performedBy: "David Kim",
        timestamp: new Date("2025-11-15"),
      },
      {
        id: "a7-3",
        action: "Milestone 'Production Line Dashboard' completed",
        performedBy: "Elena Rossi",
        timestamp: new Date("2026-01-15"),
      },
      {
        id: "a7-4",
        action: "QC module development started",
        performedBy: "Alice Chen",
        timestamp: new Date("2026-01-20"),
      },
      {
        id: "a7-5",
        action: "Project placed on hold - pending client hardware delivery",
        performedBy: "Carla Delgado",
        timestamp: new Date("2026-02-20"),
      },
    ],
  },
  {
    id: "8",
    name: "UI/UX Redesign for SaaS Dashboard",
    clientCompany: "DataViz Corp",
    industry: "IT & Software",
    serviceType: "UI/UX Design",
    status: "planning",
    priority: "medium",
    budget: 40000,
    budgetSpent: 0,
    timeline: {
      start: new Date("2026-05-01"),
      end: new Date("2026-07-15"),
    },
    progress: 0,
    assignedTeam: [teamMembers[2], teamMembers[4]],
    dueDate: new Date("2026-07-15"),
    lastUpdated: new Date("2026-03-05"),
    description:
      "Complete UI/UX redesign of DataViz Corp's analytics dashboard to improve user experience, accessibility, and data visualization clarity. Includes user research, wireframing, prototyping, and usability testing.",
    clientContact: {
      name: "Priya Sharma",
      email: "priya.sharma@dataviz.com",
      phone: "+1 (408) 555-0389",
      avatar: "PS",
    },
    milestones: [
      {
        id: "m8-1",
        title: "User Research & Interviews",
        status: "pending",
        dueDate: new Date("2026-05-15"),
      },
      {
        id: "m8-2",
        title: "Wireframing & Low-Fidelity Prototypes",
        status: "pending",
        dueDate: new Date("2026-05-30"),
      },
      {
        id: "m8-3",
        title: "High-Fidelity UI Design",
        status: "pending",
        dueDate: new Date("2026-06-15"),
      },
      {
        id: "m8-4",
        title: "Usability Testing & Iteration",
        status: "pending",
        dueDate: new Date("2026-06-30"),
      },
      {
        id: "m8-5",
        title: "Design Handoff & Documentation",
        status: "pending",
        dueDate: new Date("2026-07-15"),
      },
    ],
    files: [
      {
        id: "f8-1",
        name: "Current_Dashboard_Screenshots.zip",
        type: "image",
        size: "6.4 MB",
        uploadedBy: "Priya Sharma",
        uploadedAt: new Date("2026-03-05"),
        url: "#",
      },
      {
        id: "f8-2",
        name: "User_Feedback_Summary.pdf",
        type: "pdf",
        size: "1.2 MB",
        uploadedBy: "Priya Sharma",
        uploadedAt: new Date("2026-03-05"),
        url: "#",
      },
    ],
    activity: [
      {
        id: "a8-1",
        action: "Project proposal accepted",
        performedBy: "Carla Delgado",
        timestamp: new Date("2026-03-01"),
      },
      {
        id: "a8-2",
        action: "Initial requirements meeting held",
        performedBy: "Carla Delgado",
        timestamp: new Date("2026-03-05"),
      },
      {
        id: "a8-3",
        action: "File 'Current_Dashboard_Screenshots.zip' uploaded",
        performedBy: "Priya Sharma",
        timestamp: new Date("2026-03-05"),
      },
    ],
  },
];

export const getProjectById = (id: string): Project | undefined =>
  mockProjects.find((project) => project.id === id);
