"use client";

import { ArrowUpRight, BarChart3, BriefcaseBusiness, Clock3, type LucideIcon, MoreHorizontal } from "lucide-react";
import toast from "react-hot-toast";
import { Button } from "@/components/ui/Button";
import { Card } from "@/components/ui/Card";
import type { AdminService } from "@/types/dashboard/admin/servicesType";
import { ServiceStatusBadge } from "./ServiceStatusBadge";

export const ServicesGrid = ({ services, onToggleStatus }: { services: AdminService[]; onToggleStatus: (id: string) => void }) => {
  if (!services.length) return <div className="rounded-xl border border-dashed border-border py-14 text-center"><p className="font-medium text-heading">No services found</p><p className="mt-1 text-sm text-body">Try a different search or status filter.</p></div>;

  return <div className="grid grid-cols-1 gap-5 md:grid-cols-2 xl:grid-cols-3">{services.map((service) => <Card key={service.id} padding="base" hoverEffect className="flex flex-col"><div className="flex items-start justify-between gap-3"><div><div className="mb-2 flex items-center gap-2"><span className="rounded-md bg-muted px-2 py-1 text-xs font-semibold text-body">{service.pillar}</span><ServiceStatusBadge status={service.status} /></div><h2 className="text-lg font-semibold text-heading">{service.name}</h2></div><Button variant="ghost" size="sm" className="!p-2" onClick={() => { onToggleStatus(service.id); toast.success(`${service.name} status updated.`); }}><MoreHorizontal className="h-4 w-4" /><span className="sr-only">Update service status</span></Button></div><p className="mt-3 text-sm leading-6 text-body">{service.description}</p><div className="mt-5 grid grid-cols-2 gap-3 border-y border-border py-4"><Metric icon={BriefcaseBusiness} label="Active projects" value={String(service.activeProjects)} /><Metric icon={BarChart3} label="Lead conversion" value={`${service.conversionRate}%`} /></div><div className="mt-4 flex items-center justify-between"><div><p className="text-xs text-body">Starting price</p><p className="mt-1 text-sm font-semibold text-heading">{service.startingPrice}</p></div><div className="text-right"><p className="text-xs text-body">Delivery</p><p className="mt-1 flex items-center justify-end gap-1 text-sm font-medium text-heading"><Clock3 className="h-3.5 w-3.5 text-secondary" />{service.deliveryWindow}</p></div></div><div className="mt-4 flex flex-wrap gap-2">{service.deliverables.map((deliverable) => <span key={deliverable} className="rounded-full bg-muted px-2.5 py-1 text-xs text-body">{deliverable}</span>)}</div><div className="mt-5 flex items-center justify-between border-t border-border pt-4"><div><p className="text-xs text-body">Period revenue</p><p className="mt-0.5 font-semibold text-heading">€{service.revenue.toLocaleString()}</p></div><button type="button" onClick={() => toast.success(`${service.name} performance details will be available with backend data.`)} className="inline-flex items-center gap-1 text-sm font-semibold text-secondary hover:text-accent-hover">View performance <ArrowUpRight className="h-4 w-4" /></button></div></Card>)}</div>;
};

const Metric = ({ icon: Icon, label, value }: { icon: LucideIcon; label: string; value: string }) => <div><div className="flex items-center gap-1.5 text-xs text-body"><Icon className="h-3.5 w-3.5 text-secondary" />{label}</div><p className="mt-1 text-base font-semibold text-heading">{value}</p></div>;
