export const IMAGE = {
  aboutHeroImage: "/images/about_hero_image.avif",
  london: "/images/london.avif",
  france: "/images/france.avif",
  germany: "/images/germany.avif",
  digital_growth: "/images/Growth.jpg",
  seo_image: "/images/seo_optimaization.jpg",
  Oakstone: "/images/Oakstone.jpg",
  CloudSync: "/images/CloudSync.jpg",
  NordicTech: "/images/NordicTech.jpg",
  marketing: "/images/LL_Services-Icon_Digital-MKT.webp",
  seo: "/images/LL_Services-Icon_SEO.webp",
  management: "/images/LL_Services-Icon_PPC-CRO.webp",
  content_marketing: "/images/LL_Services-Icon_ContentMKT.webp",
  email_marketing: "/images/LL_Services-Icon_EmailMKT.webp",
  affiliate_marketing: "/images/LL_Services-Icon_Affliate.webp",
  webDevHero: "/images/web-dev-hero.avif",
  websiteMockup: "/images/website-mockup.avif",
  architectureDiagram: "/images/architecture-diagram.avif",
  dashboardPreview: "/images/dashboard-preview.avif",
  laptopMockup: "/images/laptop-mockup.avif",
  mobileHero: "/images/mobile-hero.jpg",
  phoneMockup: "/images/phone-mockup.jpg",
  appScreens: "/images/app-screens.avif",
  ecosystemDiagram: "/images/ecosystem-diagram.avif",
  userJourney: "/images/user-journey.avif",
} as const;
